import { Inter } from "next/font/google";
// import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import "./customCss/themes.scss";
import ThemeProvider from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "qulak",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <ThemeProvider >
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
